In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.cluster as cluster
from sklearn.decomposition import PCA

In [20]:
df = pd.read_csv("params_df.csv")
df.columns = ["country", "intercept", "tue", "wed", "thu", "fri", "sat", "sun", 
              "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec",
              "hours_1", "hours_2", "hours_3", "hours_4", "hours_5"]
df.set_index(df.iloc[:, 0], inplace = True)
df.drop(df.columns[0], axis = 1, inplace = True)

months = ["feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
days = ["tue", "wed", "thu", "fri", "sat", "sun"]
hours = ["hours_1", "hours_2", "hours_3", "hours_4", "hours_5"]

In [ ]:
def get_day_mean(df, day):
    if day =="mon":
        return df["intercept"] +

,intercept,tue,wed,thu,fri,sat,sun,feb,mar,apr,...,aug,sep,oct,nov,dec,hours_1,hours_2,hours_3,hours_4,hours_5
country,,,,,,,,,,,,,,,,,,,,,
POR,-0.303848,-0.144173,0.030627,0.025451,-0.005106,-0.683006,-1.025683,0.062561,-0.466553,-0.800897,...,-0.901275,-0.634060,-0.784870,-0.449313,-0.182337,0.222440,1.387414,1.652749,1.639751,1.671263
ESP,0.145691,-0.163308,0.008433,-0.012863,-0.077709,-0.707035,-1.132512,0.206270,-0.357921,-0.746375,...,-0.482026,-0.504804,-0.784689,-0.451692,-0.282497,-0.582772,1.209516,1.051712,1.116521,0.664169
FRA,1.070743,-0.122001,0.015842,0.001380,-0.046156,-0.495312,-0.716189,0.316354,-0.622126,-1.181424,...,-2.099889,-1.788107,-1.503625,-0.681222,-0.174246,-0.345722,0.615821,0.392725,0.417720,0.242967
BEL,0.453893,-0.189829,0.034236,0.024792,-0.053671,-0.774320,-1.083566,0.146724,-0.345951,-0.753857,...,-1.240171,-0.921266,-0.661347,-0.431615,-0.302832,-0.532527,1.105548,0.982282,0.991876,0.460907
CHE,1.110118,-0.096982,-0.014899,-0.038774,-0.100247,-0.636971,-0.835683,0.272736,-0.426246,-1.259853,...,-1.871806,-1.479883,-1.219798,-0.683157,-0.134408,-0.268518,0.575374,0.457593,0.331301,-0.010927
LUX,0.330413,-0.194467,-0.109017,-0.066284,0.036128,-0.551224,-1.018252,0.152297,-0.189835,-0.432633,...,-1.025138,-0.654170,-0.570100,-0.427461,-0.427820,-0.456644,0.924542,0.788895,0.794411,0.235661
NLD,0.002469,-0.098723,0.014126,0.025564,-0.034290,-0.700310,-0.998993,0.014448,-0.325137,-0.580713,...,-0.698140,-0.555007,-0.425843,-0.201980,-0.082374,-0.545838,1.362828,1.341736,1.293124,0.509548
ITA,-0.186839,-0.224697,0.023222,0.020217,-0.026114,-0.688185,-1.172161,0.202444,-0.079952,-0.428676,...,-0.400087,-0.058110,-0.208086,-0.113507,-0.225017,-0.548381,1.298174,1.118863,1.213962,0.505409
DEU,0.323337,-0.144926,0.009438,-0.028399,-0.117342,-0.883362,-1.284393,0.177465,-0.185681,-0.377155,...,-0.631100,-0.390029,-0.284841,0.006711,-0.200403,-0.792667,1.030714,0.879057,0.802816,0.047948
AUT,0.648819,-0.128648,-0.007344,-0.017087,-0.115306,-0.812070,-1.196145,0.172673,-0.240379,-0.632728,...,-0.914017,-0.660551,-0.507972,-0.214498,-0.121926,-1.040383,0.909356,0.638117,0.632011,-0.290896
DNK,0.651683,-0.054764,-0.007642,-0.005339,-0.155953,-0.700043,-0.756687,-0.096311,-0.540650,-0.954086,...,-1.043524,-1.079621,-0.684204,-0.381792,-0.217591,-0.794159,1.013778,0.799341,0.941503,-0.009702
CZE,0.800192,-0.098246,0.007589,0.011795,-0.105886,-0.865992,-1.007078,0.235484,-0.353310,-0.833066,...,-1.426866,-0.990139,-0.716620,-0.289792,-0.329816,-0.741434,0.778933,0.705449,0.634540,-0.126875
POL,0.286855,-0.173672,0.011036,-0.005246,-0.032814,-0.613372,-1.167230,0.092777,-0.276252,-0.689450,...,-0.918263,-0.677087,-0.376811,-0.209868,-0.138385,-0.638668,1.042948,1.010836,1.116924,0.409375
HUN,0.221623,-0.168818,0.034066,0.043569,-0.020865,-0.604923,-0.939416,0.162876,-0.333677,-0.638253,...,-0.794501,-0.575489,-0.419710,-0.105509,-0.198101,-0.883287,1.025045,0.976705,1.063169,0.356122
SVK,0.586712,-0.158292,0.011661,-0.001316,-0.078386,-0.699246,-0.976833,0.208524,-0.329244,-0.865958,...,-1.243637,-0.943145,-0.585952,-0.267072,-0.221562,-0.779672,0.944294,0.787529,0.872405,0.167849
SVN,0.333324,-0.164143,0.035609,0.046387,-0.037494,-0.615244,-0.892325,0.224323,-0.387478,-0.753983,...,-0.719338,-0.630224,-0.641595,-0.352763,-0.143432,-0.796313,0.988903,0.726575,0.989197,0.308617
HRV,0.103721,-0.078823,0.022121,0.017816,-0.011485,-0.305415,-0.594482,0.176786,-0.476083,-0.863327,...,-0.755140,-0.950701,-0.846164,-0.495545,0.004887,-0.660152,1.188651,1.018457,1.343069,0.843348
GRC,0.229089,-0.128668,-0.005525,0.007187,-0.039064,-0.263816,-0.608654,-0.153654,-0.715303,-1.265081,...,-0.048843,-0.862010,-1.089405,-0.680123,-0.037124,-0.414064,0.550545,0.461045,1.436780,0.647176
ALB,0.538032,-0.040519,0.023387,0.026698,-0.003224,-0.137150,-0.239968,0.029728,-0.594339,-1.216924,...,-1.692121,-1.761634,-1.339545,-0.784016,0.034985,-0.277760,0.878041,0.740048,1.133429,0.915567
MKD,0.555574,-0.048626,0.026186,0.030545,0.006035,-0.091982,-0.004862,-0.134266,-0.759588,-1.309341,...,-1.850128,-1.938013,-1.565475,-0.957121,-0.068033,-0.071018,0.811090,0.850333,1.173123,1.103094
BGR,0.750162,-0.065976,0.029696,0.026956,-0.011764,-0.275307,-0.350160,-0.016140,-0.931265,-1.580054,...,-1.631820,-1.777315,-1.445319,-0.866454,-0.126753,-0.338886,0.765932,0.676987,1.097786,0.789087
MNE,0.457232,-0.036404,0.020399,0.021519,-0.005937,-0.121871,-0.184662,0.031622,-0.610178,-1.203949,...,-1.469376,-1.728962,-1.463834,-0.920111,-0.062796,-0.279909,0.950932,0.831016,1.230483,0.990631
BIH,0.133579,-0.044923,0.023867,0.024819,0.001742,-0.130501,-0.332014,0.097225,-0.522210,-0.946541,...,-1.034047,-1.223230,-0.998101,-0.601840,0.056027,-0.541182,1.167618,1.067279,1.405848,0.924828
SRB,0.575442,-0.055643,0.024776,0.030185,-0.004105,-0.186238,-0.342718,0.043749,-0.575518,-1.199173,...,-1.740312,-1.716820,-1.235077,-0.678267,0.065271,-0.336088,0.850570,0.706387,1.095653,0.822644
ROU,0.691231,-0.164499,0.011933,0.026900,-0.029241,-0.506763,-1.003993,0.178652,-0.439974,-0.965055,...,-1.154054,-1.212766,-0.843171,-0.315601,-0.037578,-0.766705,0.650321,0.503198,0.972690,0.098822

In [17]:
df

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
POR,-0.303848,-0.144173,0.030627,0.025451,-0.005106,-0.683006,-1.025683,0.062561,-0.466553,-0.800897,...,-0.901275,-0.634060,-0.784870,-0.449313,-0.182337,0.222440,1.387414,1.652749,1.639751,1.671263
ESP,0.145691,-0.163308,0.008433,-0.012863,-0.077709,-0.707035,-1.132512,0.206270,-0.357921,-0.746375,...,-0.482026,-0.504804,-0.784689,-0.451692,-0.282497,-0.582772,1.209516,1.051712,1.116521,0.664169
FRA,1.070743,-0.122001,0.015842,0.001380,-0.046156,-0.495312,-0.716189,0.316354,-0.622126,-1.181424,...,-2.099889,-1.788107,-1.503625,-0.681222,-0.174246,-0.345722,0.615821,0.392725,0.417720,0.242967
BEL,0.453893,-0.189829,0.034236,0.024792,-0.053671,-0.774320,-1.083566,0.146724,-0.345951,-0.753857,...,-1.240171,-0.921266,-0.661347,-0.431615,-0.302832,-0.532527,1.105548,0.982282,0.991876,0.460907
CHE,1.110118,-0.096982,-0.014899,-0.038774,-0.100247,-0.636971,-0.835683,0.272736,-0.426246,-1.259853,...,-1.871806,-1.479883,-1.219798,-0.683157,-0.134408,-0.268518,0.575374,0.457593,0.331301,-0.010927
LUX,0.330413,-0.194467,-0.109017,-0.066284,0.036128,-0.551224,-1.018252,0.152297,-0.189835,-0.432633,...,-1.025138,-0.654170,-0.570100,-0.427461,-0.427820,-0.456644,0.924542,0.788895,0.794411,0.235661
NLD,0.002469,-0.098723,0.014126,0.025564,-0.034290,-0.700310,-0.998993,0.014448,-0.325137,-0.580713,...,-0.698140,-0.555007,-0.425843,-0.201980,-0.082374,-0.545838,1.362828,1.341736,1.293124,0.509548
ITA,-0.186839,-0.224697,0.023222,0.020217,-0.026114,-0.688185,-1.172161,0.202444,-0.079952,-0.428676,...,-0.400087,-0.058110,-0.208086,-0.113507,-0.225017,-0.548381,1.298174,1.118863,1.213962,0.505409
DEU,0.323337,-0.144926,0.009438,-0.028399,-0.117342,-0.883362,-1.284393,0.177465,-0.185681,-0.377155,...,-0.631100,-0.390029,-0.284841,0.006711,-0.200403,-0.792667,1.030714,0.879057,0.802816,0.047948
AUT,0.648819,-0.128648,-0.007344,-0.017087,-0.115306,-0.812070,-1.196145,0.172673,-0.240379,-0.632728,...,-0.914017,-0.660551,-0.507972,-0.214498,-0.121926,-1.040383,0.909356,0.638117,0.632011,-0.290896
DNK,0.651683,-0.054764,-0.007642,-0.005339,-0.155953,-0.700043,-0.756687,-0.096311,-0.540650,-0.954086,...,-1.043524,-1.079621,-0.684204,-0.381792,-0.217591,-0.794159,1.013778,0.799341,0.941503,-0.009702
CZE,0.800192,-0.098246,0.007589,0.011795,-0.105886,-0.865992,-1.007078,0.235484,-0.353310,-0.833066,...,-1.426866,-0.990139,-0.716620,-0.289792,-0.329816,-0.741434,0.778933,0.705449,0.634540,-0.126875
POL,0.286855,-0.173672,0.011036,-0.005246,-0.032814,-0.613372,-1.167230,0.092777,-0.276252,-0.689450,...,-0.918263,-0.677087,-0.376811,-0.209868,-0.138385,-0.638668,1.042948,1.010836,1.116924,0.409375
HUN,0.221623,-0.168818,0.034066,0.043569,-0.020865,-0.604923,-0.939416,0.162876,-0.333677,-0.638253,...,-0.794501,-0.575489,-0.419710,-0.105509,-0.198101,-0.883287,1.025045,0.976705,1.063169,0.356122
SVK,0.586712,-0.158292,0.011661,-0.001316,-0.078386,-0.699246,-0.976833,0.208524,-0.329244,-0.865958,...,-1.243637,-0.943145,-0.585952,-0.267072,-0.221562,-0.779672,0.944294,0.787529,0.872405,0.167849
SVN,0.333324,-0.164143,0.035609,0.046387,-0.037494,-0.615244,-0.892325,0.224323,-0.387478,-0.753983,...,-0.719338,-0.630224,-0.641595,-0.352763,-0.143432,-0.796313,0.988903,0.726575,0.989197,0.308617
HRV,0.103721,-0.078823,0.022121,0.017816,-0.011485,-0.305415,-0.594482,0.176786,-0.476083,-0.863327,...,-0.755140,-0.950701,-0.846164,-0.495545,0.004887,-0.660152,1.188651,1.018457,1.343069,0.843348
GRC,0.229089,-0.128668,-0.005525,0.007187,-0.039064,-0.263816,-0.608654,-0.153654,-0.715303,-1.265081,...,-0.048843,-0.862010,-1.089405,-0.680123,-0.037124,-0.414064,0.550545,0.461045,1.436780,0.647176
ALB,0.538032,-0.040519,0.023387,0.026698,-0.003224,-0.137150,-0.239968,0.029728,-0.594339,-1.216924,...,-1.692121,-1.761634,-1.339545,-0.784016,0.034985,-0.277760,0.878041,0.740048,1.133429,0.915567
MKD,0.555574,-0.048626,0.026186,0.030545,0.006035,-0.091982,-0.004862,-0.134266,-0.759588,-1.309341,...,-1.850128,-1.938013,-1.565475,-0.957121,-0.068033,-0.071018,0.811090,0.850333,1.173123,1.103094
BGR,0.750162,-0.065976,0.029696,0.026956,-0.011764,-0.275307,-0.350160,-0.016140,-0.931265,-1.580054,...,-1.631820,-1.777315,-1.445319,-0.866454,-0.126753,-0.338886,0.765932,0.676987,1.097786,0.789087
MNE,0.457232,-0.036404,0.020399,0.021519,-0.005937,-0.121871,-0.184662,0.031622,-0.610178,-1.203949,...,-1.469376,-1.728962,-1.463834,-0.920111,-0.062796,-0.279909,0.950932,0.831016,1.230483,0.990631
BIH,0.133579,-0.044923,0.023867,0.024819,0.001742,-0.130501,-0.332014,0.097225,-0.522210,-0.946541,...,-1.034047,-1.223230,-0.998101,-0.601840,0.056027,-0.541182,1.167618,1.067279,1.405848,0.924828
SRB,0.575442,-0.055643,0.024776,0.030185,-0.004105,-0.186238,-0.342718,0.043749,-0.575518,-1.199173,...,-1.740312,-1.716820,-1.235077,-0.678267,0.065271,-0.336088,0.850570,0.706387,1.095653,0.822644
ROU,0.691231,-0.164499,0.011933,0.026900,-0.029241,-0.506763,-1.003993,0.178652,-0.439974,-0.965055,...,-1.154054,-1.212766,-0.843171,-0.315601,-0.037578,-0.766705,0.650321,0.503198,0.972690,0.098822

In [8]:
X = df.iloc[:, 1:].to_numpy()

(25, 23)